openapi: 3.0.0
info:
  description: |
    U ovom dokumentu su navedeni API-ji koje nudi modul profesori.
  version: "1.0.0-oas3"
  title: Mikroservisi modula profesori
tags:
  - name: prisustvo
    description: Svi mikroservisi vezani za prisustvo
  - name: bodoviIspiti
    description: Svi mikroservisi vezani za bodove ostvarene na ispitima
  - name: ocjene
    description: Svi mikroservisi vezani za ocjene
  - name: teme
    description: Svi mikroservisi vezani za teme završnih radova
paths:
  '/fox/bodoviPrisustvo/{idStudenta}/{idPredmeta}':
    get:
      tags:
        - prisustvo
      summary: Dobavlja bodove studenta ostvarene na prisustvo na željenom predmetu
      description: >-
        Ovaj endpoint dobavljabroj bodova studenta ostvarenih na prisustvo na
        predmetu sa id-em idPredmeta.
      operationId: getBodoviPrisustvo
      parameters:
        - name: idStudenta
          in: path
          description: id studenta za kojeg trazimo prisustvo
          required: true
          schema:
            type: integer
            format: int64
        - name: idPredmeta
          in: path
          description: id predmeta za kojeg trazimo prisustvo
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Not found
  /fox/prisustvoPredavanja:
    post:
      tags:
        - prisustvo
      summary: Upisuje se prisustvo studentu na predavanjima
      operationId: addPrisustvoPredavanja
      responses:
        '405':
          description: Invalid input
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrisustvoPredavanja'
        description: Vrijednost koja se unosi za prisustvo na predavanjima studentu
        required: true
  /fox/prisustvoVjezbe:
    post:
      tags:
        - prisustvo
      summary: Upisuje se prisustvo studentu na vjezbama
      operationId: addPrisustvoVjezbe
      responses:
        '405':
          description: Invalid input
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrisustvoVjezbe'
        description: Vrijednost koja se unosi za prisustvo studentu na vjezbama
        required: true
  /fox/prisustvoTutorijali:
    post:
      tags:
        - prisustvo
      summary: Upisuje se prisustvo studentu na tutorijalima
      operationId: addPrisustvoTutorijali
      responses:
        '405':
          description: Invalid input
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrisustvoTutorijali'
        description: Vrijednost koja se unosi za prisustvo studentu na tutorijalima
        required: true
  '/fox/prisustvoPredavanja/{idStudenta}/{idPredmeta}/{brojSedmice}':
    get:
      tags:
        - prisustvo
      summary: Pronadji vrijednost prisustva na predavanjima
      description: >-
        Vraća da, ne ili null na prisustvo na predavanjima za odgovarajuću
        sedmicu, studenta i predmet.
      operationId: getPrisustvoPredavanja
      parameters:
        - name: idStudenta
          in: path
          description: id studenta za kojeg trazimo prisustvo
          required: true
          schema:
            type: integer
            format: int64
        - name: idPredmeta
          in: path
          description: id predmeta za kojeg trazimo prisustvo
          required: true
          schema:
            type: integer
            format: int64
        - name: brojSedmice
          in: path
          description: broj sedmice za koju trazimo prisustvo
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrisustvoPredavanja'
        '400':
          description: Invalid ID supplied
        '404':
          description: Not found
  '/fox/prisustvoVjezbe/{idStudenta}/{idPredmeta}/{brojSedmice}':
    get:
      tags:
        - prisustvo
      summary: Pronadji vrijednost prisustva na vjezbama
      description: >-
        Vraća da, ne ili null na prisustvo na vjezbama za odgovarajuću sedmicu,
        studenta i predmet.
      operationId: getPrisustvoVjezbe
      parameters:
        - name: idStudenta
          in: path
          description: id studenta za kojeg trazimo prisustvo
          required: true
          schema:
            type: integer
            format: int64
        - name: idPredmeta
          in: path
          description: id predmeta za kojeg trazimo prisustvo
          required: true
          schema:
            type: integer
            format: int64
        - name: brojSedmice
          in: path
          description: broj sedmice za koju trazimo prisustvo
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrisustvoPredavanja'
        '400':
          description: Invalid ID supplied
        '404':
          description: Not found
  '/fox/prisustvoTutorijali/{idStudenta}/{idPredmeta}/{brojSedmice}':
    get:
      tags:
        - prisustvo
      summary: Pronadji vrijednost prisustva na tutorijalima
      description: >-
        Vraća da, ne ili null na prisustvo na tutorijalima za odgovarajuću
        sedmicu, studenta i predmet.
      operationId: getPrisustvoTutorijali
      parameters:
        - name: idStudenta
          in: path
          description: id studenta za kojeg trazimo prisustvo
          required: true
          schema:
            type: integer
            format: int64
        - name: idPredmeta
          in: path
          description: id predmeta za kojeg trazimo prisustvo
          required: true
          schema:
            type: integer
            format: int64
        - name: brojSedmice
          in: path
          description: broj sedmice za koju trazimo prisustvo
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrisustvoPredavanja'
        '400':
          description: Invalid ID supplied
        '404':
          description: Not found
  /fox/bodoviIspit:
    post:
      tags:
        - bodoviIspiti
      summary: Upisuje se broj bodova ostvarenih na odgovarajućem ispitu za studenta
      operationId: addBodoviIspit
      responses:
        '405':
          description: Invalid input
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BodoviIspit'
        description: Vrijednost koja se unosi za broj bodova studentu
        required: true
  '/fox/bodoviIspit/{idStudenta}/{idPredmeta}/{idIspita}':
    get:
      tags:
        - bodoviIspiti
      summary: Pronadji broj bodova na navedenom ispiu za odgovarajuceg studenta
      description: Vraća broj bodova koje je student ostvario na ispitu.
      operationId: getBrojBodova
      parameters:
        - name: idStudenta
          in: path
          description: id studenta za kojeg trazimo broj bodova
          required: true
          schema:
            type: integer
            format: int64
        - name: idPredmeta
          in: path
          description: id predmeta
          required: true
          schema:
            type: integer
            format: int64
        - name: idIspita
          in: path
          description: id ispita
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BodoviIspit'
        '400':
          description: Invalid ID supplied
        '404':
          description: Not found
  /fox/ocjene/ocjena:
    post:
      tags:
        - ocjene
      summary: Upisuje se ocjena studentu
      operationId: addOcjena
      responses:
        '405':
          description: Invalid input
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ocjena'
        description: Vrijednost koja se unosi za ocjenu studentu
        required: true
  '/fox/ocjena/{idStudenta}/{idPredmeta}':
    get:
      tags:
        - ocjene
      summary: Pronadji ocjenu za odgovarajuceg studenta
      description: Vraća ocjenu studenta na navedenom predmetu.
      operationId: getOcjena
      parameters:
        - name: idStudenta
          in: path
          description: id studenta za kojeg trazimo broj bodova
          required: true
          schema:
            type: integer
            format: int64
        - name: idPredmeta
          in: path
          description: id predmeta
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ocjena'
        '400':
          description: Invalid ID supplied
        '404':
          description: Not found
  '/fox/teme/{idPredmeta}':
    get:
      tags:
        - teme
      summary: Pronadji teme za predmet
      description: Vraća sve teme na navedenom predmetu.
      operationId: getTeme
      parameters:
        - name: idPredmeta
          in: path
          description: id predmeta
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Lista tema
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tema'
        '400':
          description: Invalid ID supplied
        '404':
          description: Not found
  /fox/teme/novaTema:
    post:
      tags:
        - teme
      summary: Upisuje se nova tema sa opisom
      operationId: addTema
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '404':
          description: Not found
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NovaTema'
        description: Vrijednost koja se unosi za ocjenu studentu
        required: true
  '/fox/teme/izmjeniTemu/{idTeme}':
    put:
      tags:
        - teme
      summary: Izmjeni temu
      description: Mijenja temu sa id-em idTeme
      operationId: updateTema
      parameters:
        - name: idTeme
          in: path
          description: id teme
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
        '400':
          description: Invalid ID supplied
        '404':
          description: Not found
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTeme'
        description: Vrijednost koja se unosi za ocjenu studentu
        required: true
  '/fox/teme/izbrisiTemu/{idTeme}':
    delete:
      tags:
        - teme
      summary: Izbrisi temu
      description: Brise temu sa id-em idTeme
      operationId: deleteTema
      parameters:
        - name: idTeme
          in: path
          description: id teme
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
        '400':
          description: Invalid ID supplied
        '404':
          description: Not found
  '/fox/zahtjevi/{idProfesora}':
    get:
      tags:
        - teme
      summary: Pronadji teme za predmet
      description: Vraća sve zahtjeve za teme za navedenog profesora.
      operationId: getZahtjevi
      parameters:
        - name: idProfesora
          in: path
          description: id prrofesora
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Lista zahtjeva
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Zahtjev'
        '400':
          description: Invalid ID supplied
        '404':
          description: Not found
  /fox/teme/dodajZahtjev:
    post:
      tags:
        - teme
      summary: Dodaje se novi zahtjev za završni rad
      operationId: addZahtjev
      responses:
        '405':
          description: Invalid input
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoviZahtjev'
        description: Vrijednosti novog zahtjeva
        required: true
  '/fox/teme/odobri/{idTeme}':
    put:
      tags:
        - teme
      summary: Odobri zahtjev za završni
      description: Odobrava zahtjev za temu završnog rada
      operationId: odobriZahtjev
      parameters:
        - name: idTeme
          in: path
          description: id teme
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
        '400':
          description: Invalid ID supplied
        '404':
          description: Not found
  '/fox/teme/izbrisiZahtjev/{idTeme}':
    delete:
      tags:
        - teme
      summary: Izbrisi zahtjev za temu
      description: Brise zahtjev za temu sa id-em idTeme
      operationId: deleteZahtjev
      parameters:
        - name: idTeme
          in: path
          description: id teme
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
        '400':
          description: Invalid ID supplied
        '404':
          description: Not found
servers:
  - url: 'https://virtserver.swaggerhub.com/dsabovic1/ProfesoriMikroservisi/1.0.0'
  - url: 'http://virtserver.swaggerhub.com/dsabovic1/ProfesoriMikroservisi/1.0.0'
components:
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
          scopes:
            'write:pets': modify pets in your account
            'read:pets': read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
  schemas:
    PrisustvoPredavanja:
      type: object
      properties:
        idStudenta:
          type: integer
          format: int64
        idPredmeta:
          type: integer
          format: int64
        prisutan:
          type: boolean
          default: false
        brojSedmice:
          type: integer
          format: int32
    PrisustvoVjezbe:
      type: object
      properties:
        idStudenta:
          type: integer
          format: int64
        idPredmeta:
          type: integer
          format: int64
        prisutan:
          type: boolean
          default: false
        brojSedmice:
          type: integer
          format: int32
    PrisustvoTutorijali:
      type: object
      properties:
        idStudenta:
          type: integer
          format: int64
        idPredmeta:
          type: integer
          format: int64
        prisutan:
          type: boolean
          default: false
        brojSedmice:
          type: integer
          format: int32
    BodoviIspit:
      type: object
      properties:
        idStudenta:
          type: integer
          format: int64
        idIspita:
          type: integer
          format: int64
        idPredmeta:
          type: integer
          format: int64
        bodovi:
          type: integer
          format: int32
    Ocjena:
      type: object
      properties:
        idStudent:
          type: integer
          format: int64
        idPredmet:
          type: integer
          format: int64
        idAkademskaGodina:
          type: integer
          format: int32
        ocjena:
          type: integer
          format: int32
        datum_upisa:
          type: string
          format: date
    Tema:
      type: object
      properties:
        id:
          type: integer
          format: int64
        naziv:
          type: string
        opis:
          type: string
    Zahtjev:
      type: object
      properties:
        id:
          type: integer
          format: int64
        idTema:
          type: integer
          format: int64
        idStudent:
          type: integer
          format: int64
        idProfesor:
          type: integer
          format: int64
        odobreno:
          type: string
    NoviZahtjev:
      type: object
      properties:
        idTema:
          type: integer
          format: int64
        idStudent:
          type: integer
          format: int64
        idProfesor:
          type: integer
          format: int64
        odobreno:
          type: string
    NovaTema:
      type: object
      properties:
        naziv:
          type: string
        opis:
          type: string
        idProfesora:
          type: integer
          format: int64
        idPredmeta:
          type: integer
          format: int64
    UpdateTeme:
      type: object
      properties:
        naziv:
          type: string
        opis:
          type: string